version: '3'
services:
      
  order-service-1:
    image: order-service
    ports:
      - 8081:8081
    environment:
      APP_PORT: 8081
      DB_URL: 10.0.2.15:5432
      KEYCLOAK_URL: http://10.0.2.15:8082
      LOGSTASH_URL: 10.0.2.15:12202
      ORDER_SERVICE_URL: http://10.0.2.15/order-service
      CONSUL_URL: http://10.0.2.15:8500
      
  order-service-2:
    image: order-service
    ports:
      - 8086:8086
    environment:
      APP_PORT: 8086
      DB_URL: 10.0.2.15:5432
      KEYCLOAK_URL: http://10.0.2.15:8082
      LOGSTASH_URL: 10.0.2.15:12202
      ORDER_SERVICE_URL: http://10.0.2.15/order-service
      CONSUL_URL: http://10.0.2.15:8500
