version: '3'
services:
      
  manage-service-1:
    image: manage-service
    ports:
      - 8083:8083
    environment:
      APP_PORT: 8083
      DB_URL: 10.0.2.15:5432
      KEYCLOAK_URL: http://10.0.2.15:8082
      LOGSTASH_URL: 10.0.2.15:12202
      ORDER_SERVICE_URL: http://10.0.2.15/order-service
      CONSUL_URL: http://10.0.2.15:8500
  
  manage-service-2:
    image: manage-service
    ports:
      - 8085:8085
    environment:
      APP_PORT: 8085
      DB_URL: 10.0.2.15:5432
      KEYCLOAK_URL: http://10.0.2.15:8082
      LOGSTASH_URL: 10.0.2.15:12202
      ORDER_SERVICE_URL: http://10.0.2.15/order-service
      CONSUL_URL: http://10.0.2.15:8500
